### PR TITLE
Added a check for ssh key authetication

### PR DESCRIPTION
**Pull request by jjasghar**
It seems there was a race condition, this method checks for ssh key
authentication before continuing the run.

With the help of @adamleff we were able to get this done.

### CODE REVIEW

**Comment by adamleff** [comment]
Minor rubocop things, nothing I would hold this up for.  If remaining functionality still looks good to you, I'm :+1: on the change. :)

**Comment by jjasghar** [comment]
Grrr rubocop...yeah ill get those fixed here and then run the suite. I'll mark this as WIP.

**Comment by jjasghar** [comment]
These tests now fail:

```ruby
  #create
    required options provided
      generates a server name in the absence of one (FAILED - 1)
      gets a proper server ID (FAILED - 2)
      gets a proper hostname (IP) (FAILED - 3)
      does not disable SSL validation (FAILED - 4)
    SSL validation disabled
      disables SSL cert validation (FAILED - 5)
```

**Comment by ramereth** [comment]
@jjasghar any update on this PR? We're running into this causing us a lot of trouble. Let me know if there's anything we can do to help.

**Comment by jjasghar** [comment]
Wow, this completely fell through the cracks. I'll get this reprioritized.

**Comment by jjasghar** [comment]
Released via 1.9.0.dev, please test and report issues: https://github.com/test-kitchen/kitchen-openstack/issues/93

**Pull request merged**
