### PR TITLE
Added ability to specify metadata on the create_server call

### PR DESCRIPTION
**Pull request by levisaya**

### CODE REVIEW

**Comment by AStrangeEnigma** [comment]
@jjasghar I'd really like to see this get merged! It looks the building is failing for something trivial, just need to change

metadata: {'hi' => 'there'}

on lines 766 and 776.

@levisaya Thanks for your work! :)

**Comment by jjasghar** [comment]
@AStrangeEnigma awesome, thanks for the poke on this. I need to rebuild my test environment, but as soon as I can, and I verify this, i'll merge and release a `pre` kitchen-openstack gem.

**Comment by jjasghar** [comment]
Please rebase off the upstream changes.

**Comment by jjasghar** [comment]
Closing due to probably abandoned.

**Pull request closed without merging**
