### PR TITLE
Ability to control the order of IP to connect to

### PR DESCRIPTION
**Pull request by ytsarev**

### CODE REVIEW

**Comment by ytsarev** [comment]
@RoboticCheese could you please review ?

**Comment by jjasghar** [comment]
Gonna take a look at this today. 2015-08-03

**Comment by jjasghar** [comment]
Can you add to the readme an example of the .yml using it? I don't think it's obvious from reading it on the readme.

**Comment by ytsarev** [comment]
@jjasghar thanks for the point, I've added the example. Hopefully it is illustrative enough.

**Comment by jjasghar** [comment]
Perfect. I'm gonna merge this and ping @RoboticCheese to start thinking about getting a release done. :)

**Pull request merged**
