### PR TITLE
Update to check IP version when using `openstack_network_name`.

### PR DESCRIPTION
**Pull request by nmische**
Addresses #141.

### CODE REVIEW

**Comment by jjasghar** [comment]
:metal: great addition. Can you add to the documentation and tests for this too please?

**Comment by jjasghar** [comment]
Also please address the failing test(s).

**Comment by jjasghar** [comment]
Awesome! I'll put a release together here soon, thanks for the PR! :metal:

**Comment by nmische** [comment]
Any update on when this may get released? Thanks!

**Comment by jjasghar** [comment]
I've been at OpenStack summit recently, I should be verifying it and releasing this week.

**Comment by trumant** [comment]
Would like to see this merged and released soon, any luck getting to that @jjasghar ?

**Comment by jjasghar** [comment]
I need to do some final testing before the release, should be today/tomorrow ideally.

**Pull request merged**
