### PR TITLE
Implement Openstack Block Device Storage

### PR DESCRIPTION
**Pull request by LiamHaworth**
I have made a pull request a few months ago to merge my block storage code into the driver but it was denied because the tests were failing.

Finally I have taken the time to completely re-write my code and also write the tests as well, I have tested my code and it is completely working against Icehouse and Juno

### CODE REVIEW

**Comment by LiamHaworth** [comment]
Ok, that failure I am stumped on o_O

**Comment by LiamHaworth** [comment]
Turns out this is because there has been some major code changes between test-kitchen 1.2.1 and 1.3.1

**Comment by jssnirmal** [comment]
:+1:

**Comment by nimeshsubramanian** [comment]
awesome stuff!! Just tested it out. I wanted this functionality for a really long time.

Thanks again.

**Comment by david-crowder** [comment]
+1

**Comment by LiamHaworth** [comment]
@RoboticCheese any chance of getting this merged?

**Comment by ryancragun** [comment]
@LiamHaworth Is there any chance you could rebase the PR and fixup/squash some of those commits?  Otherwise, LGTM.

**Comment by RoboticCheese** [comment]
Hi! So, I finally had some time to go over this. Works great against a DevStack VM so I've gone ahead and merged it (with some of the commits squashed for a cleaner history).

Rackspace (the only production OpenStack environment I have access to) doesn't seem to like it, though. While they do have OpenStack block storage, it seems they don't allow you to specify volumes when creating a server--you have to attach them after the fact. Not sure how common this might be in the OpenStack world, but I'm looking into supporting that with these same config keys before cutting a release, unless it starts getting too nasty.

@LiamHaworth Do you remember offhand what issue(s) you were seeing with Kitchen 1.3 that necessitated pinning to 1.2? I'd like to fix that before cutting a new release as well. Thanks!

**Comment by LiamHaworth** [comment]
@RoboticCheese The problem I was facing is that when I ran the test's it would trip up on every instances of `instance`

**Comment by jjasghar** [comment]
Could you rebase this off master for me, and squash the commits? This seems like something we should have support for.

**Comment by jjasghar** [comment]
@LiamHaworth any chance you can rebase off master for me?

**Comment by LiamHaworth** [comment]
Why is the rebase required? As far as i was aware this had been marged into master with some commits squashed

**Comment by jjasghar** [comment]
hmm, ok. maybe i've missed something then. Thank :D I was just trying to clean some things up.

**Comment by LiamHaworth** [comment]
Yeah, 6 months ago @RoboticCheese made comment about it

**Comment by lgeinert** [comment]
Does anyone know if this driver can support the creation of two block devices?

**Comment by LiamHaworth** [comment]
No, it doesn't support creating two block devices due to the limitation of the OpenStack API itself iirc

**Pull request closed without merging**
